services:
#    recoco_web.example:
#        class: Recoco\WebBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    recoco.domain.gnavi.usecase.save_rest:
        class: Recoco\Domain\Gnavi\Usecase\SaveRest
        arguments: ["@recoco.infrastructure.gnavi.repository.rest"]

    recoco.domain.gnavi.usecase.get_near_rests:
        class: Recoco\Domain\Gnavi\Usecase\GetNearRests
        arguments: ["@recoco.infrastructure.gnavi.repository.rest"]

    recoco.infrastructure.gnavi.repository.rest:
        class: Recoco\Infrastructure\Gnavi\Repository\RestRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - Recoco\Domain\Gnavi\Entity\Rest

    recoco.infrastructure.api.serializer.json:
        class: Recoco\Infrastructure\Api\Serializer\JsonSerializer
        arguments: ["@recoco.infrastructure.api.serializer.builder"]

    recoco.infrastructure.api.serializer.builder:
        class: Recoco\Infrastructure\Api\Serializer\SerializerBuilder
