services:
#    recoco_web.example:
#        class: Recoco\WebBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    recoco.domain.gnavi.service.gnavi_api.service:
        class: Recoco\Domain\Gnavi\Service\GnaviApiService
        arguments: []

    recoco.domain.gnavi.usecase.save_rest:
        class: Recoco\Domain\Gnavi\Usecase\SaveRest
        arguments: ["@recoco.infrastructure.gnavi.repository.rest"]

    recoco.infrastructure.gnavi.repository.rest:
        class: Recoco\Infrastructure\Gnavi\Repository\RestRepository
        arguments: ["@doctrine.orm.entity_manager"]
