version: '2'

services:
  db:
    container_name: recoco-db
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: recoco_root
      MYSQL_DATABASE: recoco
      MYSQL_USER: recoco
      MYSQL_PASSWORD: recoco

  db-admin:
    container_name: recoco-db-admin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
        - "8080:80"
        
  web:
    container_name: recoco-web
    build: ./web
    depends_on:
      - db
    volumes:
      - ../:/var/www/html
    ports:
      - '80:80'
